import os

BOT_TOKEN = os.getenv("BOT_TOKEN", "YOUR_TOKEN_HERE")
DB_PATH = "arabic_bot.db"
WORDS_PATH = "data/words.json"
WORDS_PER_LESSON = 10
WORDS_PER_WEEK = 70
WEEKLY_TEST_COUNT = 25
MAX_FAILURES = 3
